### ISSUE TITLE
Broken Fedora 38 (only?) build

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/ILLIXR#427]
As mentioned in #426, the build is currently broken for Fedora 38 for both:
1. Running the included docker workflow `podman build -t illixr-fedora-38-cmake-build -f docker/fedora/38/Dockerfile .`, and
2. Running this new container [worfklow](https://github.com/e3m3/ILLIXR/blob/issue-broken-fedora38/container/Containerfile.fedora38) `podman build -t illixr-fedora-38 -f container/Containerfile.fedora38 .`

For the included workflow (1.) the following error occurs: 
```
STEP 5/12: RUN sed -i 's/^[ \t]*//g' /usr/lib64/pkgconfig/*
--> f837f749c2a9
STEP 6/12: RUN ln -s /usr/include /include
--> 8b8a954f2724
STEP 7/12: RUN useradd -ms /bin/bash illixr
--> c8d889531041
STEP 8/12: USER illixr
--> f08f1ec67e2c
STEP 9/12: WORKDIR /home/illixr
--> 004a7cf15e75
STEP 10/12: RUN git clone -b convertBuildToCmake https://github.com/ILLIXR/ILLIXR.git
Cloning into 'ILLIXR'...
--> 58f2e3985b76
STEP 11/12: COPY --chown=illixr cmk.sh .
Error: building at STEP "COPY --chown=illixr cmk.sh .": checking on sources under "/var/tmp/libpod_builder1235855811/build": copier: stat: "/cmk.sh": no such file or directory
```

For the new workflow (2.) from this [issue branch](https://github.com/e3m3/ILLIXR/tree/issue-broken-fedora38) and after adding [missing dependencies](https://github.com/e3m3/ILLIXR/blob/feae9c527e87b980577bf97dbae213d4857646d8/container/Containerfile.fedora38#L33) not found in `getting_started.md`, the following error occurs:
```
-- Could NOT find jack (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Configuring done (1.1s)
-- Generating done (0.0s)
-- Build files have been written to: /root/project/build/_deps/portaudio/src/PortAudio-build
[16/57] Building CXX object plugins/gldemo/CMakeFiles/plugin.gldemo.opt.dir/plugin.cpp.o
FAILED: plugins/gldemo/CMakeFiles/plugin.gldemo.opt.dir/plugin.cpp.o
/usr/bin/c++ -DFMT_SHARED -DGLSL_VERSION=\"330\" -DILLIXR_BUILD_SUFFIX=.opt -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -Dplugin_gldemo_opt_EXPORTS -I/root/project/include -O3 -DNDEBUG -Wall -Wextra -Wno-attributes -Wno-unknown-pragmas -fPIC -std=gnu++17 -fPIC -MD -MT plugins/gldemo/CMakeFiles/plugin.gldemo.opt.dir/plugin.cpp.o -MF plugins/gldemo/CMakeFiles/plugin.gldemo.opt.dir/plugin.cpp.o.d -o plugins/gldemo/CMakeFiles/plugin.gldemo.opt.dir/plugin.cpp.o -c /root/project/plugins/gldemo/plugin.cpp
In file included from /root/project/include/illixr/gl_util/obj.hpp:11,
                 from /root/project/plugins/gldemo/plugin.cpp:8:
/root/project/include/illixr/gl_util/lib/stb_image.h: In function 'void* stbi__load_gif_main(stbi__context*, int**, int*, int*, int*, int*, int)':
/root/project/include/illixr/gl_util/lib/stb_image.h:6778:11: warning: variable 'out_size' set but not used [-Wunused-but-set-variable]
 6778 |       int out_size = 0;
      |           ^~~~~~~~
/root/project/include/illixr/gl_util/lib/stb_image.h:6779:11: warning: variable 'delays_size' set but not used [-Wunused-but-set-variable]
 6779 |       int delays_size = 0;
      |           ^~~~~~~~~~~
/root/project/include/illixr/gl_util/obj.hpp: In constructor 'ILLIXR::ObjScene::ObjScene(const std::string&, const std::string&)':
/root/project/include/illixr/gl_util/obj.hpp:211:64: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
  211 |                 if (shapes[shape_idx].mesh.material_ids.size() >= 0) {
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
In file included from /usr/include/spdlog/fmt/fmt.h:31,
                 from /usr/include/spdlog/common.h:45,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /root/project/include/illixr/error_util.hpp:10,
                 from /root/project/include/illixr/cpu_timer.hpp:5,
                 from /root/project/include/illixr/switchboard.hpp:11,
                 from /root/project/include/illixr/data_format.hpp:10,
                 from /root/project/plugins/gldemo/plugin.cpp:5:
/usr/include/fmt/core.h: In instantiation of 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_value(T&&) [with Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; T = const unsigned char*&]':
/usr/include/fmt/core.h:1777:29:   required from 'constexpr fmt::v9::detail::value<Context> fmt::v9::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; type <anonymous> = fmt::v9::detail::type::custom_type; T = const unsigned char*; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/usr/include/fmt/core.h:1901:77:   required from 'constexpr fmt::v9::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const unsigned char*}; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; Args = {const unsigned char*}]'
/usr/include/fmt/core.h:1918:31:   required from 'constexpr fmt::v9::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<Args>::type>::type ...> fmt::v9::make_format_args(Args&& ...) [with Context = basic_format_context<appender, char>; Args = {const unsigned char*}]'
/usr/include/spdlog/logger.h:374:75:   required from 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, spdlog::string_view_t, Args&& ...) [with Args = {const unsigned char*}; spdlog::string_view_t = fmt::v9::basic_string_view<char>]'
/usr/include/spdlog/logger.h:90:13:   required from 'void spdlog::logger::log(spdlog::source_loc, spdlog::level::level_enum, fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const unsigned char*}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const unsigned char*>]'
/usr/include/spdlog/logger.h:96:12:   required from 'void spdlog::logger::log(spdlog::level::level_enum, fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const unsigned char*}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const unsigned char*>]'
/usr/include/spdlog/logger.h:170:12:   required from 'void spdlog::logger::error(fmt::v9::format_string<T ...>, Args&& ...) [with Args = {const unsigned char*}; fmt::v9::format_string<T ...> = fmt::v9::basic_format_string<char, const unsigned char*>]'
/root/project/plugins/gldemo/plugin.cpp:302:37:   required from here
/usr/include/fmt/core.h:1751:17: error: static assertion failed: Formatting of non-void pointers is disallowed.
 1751 |   static_assert(formattable_pointer,
      |                 ^~~~~~~~~~~~~~~~~~~
/usr/include/fmt/core.h:1751:17: note: 'formattable_pointer' evaluates to false
```

I believe this bug is also reproducible in later Fedora versions (> 38). This might be due to drifting dependency versions from when the tutorial/docker workflows were originally developed.

Minimally, the missing dependencies should be added to the `getting_started.md` and/or untested distros should be removed from the supported/tested list if this will not be addressed.

**Comment by e3m3** [comment]
Disabling the spdlogger dependency using the CMake option introduced in #426 allowed forward progress on the build.

**Comment by e3m3** [comment]
As shown [here](https://github.com/e3m3/ILLIXR/blob/feae9c527e87b980577bf97dbae213d4857646d8/container/Containerfile.fedora38#L28) the [proposed solution](https://github.com/ILLIXR/ILLIXR/pull/426#issuecomment-2430684719) in #426 of installing the missing dependency is not sufficient resolve the spdlogger build issue.

**Comment by e3m3** [comment]
> 1. Running the included docker workflow `podman build -t illixr-fedora-38-cmake-build -f docker/fedora/38/Dockerfile .`, and

This build was resolved by running the build script from the `docker` directory rather than the root (`podman build -t illixr-fedora-38-cmake-build -f docker/fedora/38/Dockerfile docker`) and adding `spdlog-devel` to the Dockerfile `(docker/fedora/38/Dockerfile)` as suggested. One issue is that the missing spdlogger dependency was easier to add directly to the `dnf` call in the Dockerfile rather than installing it post build because no password is set for the `illixr` user during setup. This should be added rather than requiring it implicitly.

Another issue is that some subset of dependencies installed in `docker/fedora/38/Dockerfile` appear to be implicitly required to build the spdlogger dependency for ILLIXR such that installing `spdlog-devel` is not sufficient as discussed above. It's not clear without digging which dependency resolved the spdlog build, but the dependencies installed in the Docker builds should be synced with the `getting_started.md` selected dependencies for each distro to avoid confusion for new users. Alternatively, the containerized Docker builds should be referenced as the canonical way to build ILLIXR if this is the intended default workflow.

**Comment by e3m3** [comment]
> > 1. Running the included docker workflow `podman build -t illixr-fedora-38-cmake-build -f docker/fedora/38/Dockerfile .`, and
> 
> This build was resolved by running the build script from the `docker` directory rather than the root (`podman build -t illixr-fedora-38-cmake-build -f docker/fedora/38/Dockerfile docker`) and adding `spdlog-devel` to the Dockerfile `(docker/fedora/38/Dockerfile)` as suggested. One issue is that the missing spdlogger dependency was easier to add directly to the `dnf` call in the Dockerfile rather than installing it post build because no password is set for the `illixr` user during setup. This should be added rather than requiring it implicitly.
> 
> Another issue is that some subset of dependencies installed in `docker/fedora/38/Dockerfile` appear to be implicitly required to build the spdlogger dependency for ILLIXR such that installing `spdlog-devel` is not sufficient as discussed above. It's not clear without digging which dependency resolved the spdlog build, but the dependencies installed in the Docker builds should be synced with the `getting_started.md` selected dependencies for each distro to avoid confusion for new users. Alternatively, the containerized Docker builds should be referenced as the canonical way to build ILLIXR if this is the intended default workflow.

After porting the Dockerfile code to the new workflow by adding the [missing dependencies](https://github.com/e3m3/ILLIXR/blob/dbe2881d8ddd9b5639766d48ecf5488340b9b667/container/Containerfile.fedora38#L32), the build still encounters the same build issue with spdlogger mentioned above for the workflow (2.). This means the issue is not implicitly missing dependencies in the Dockerfile compared to `getting_started.md`, but rather something else is wrong with this seemingly normal CMake build workflow shown in this [build](https://github.com/e3m3/ILLIXR/blob/dbe2881d8ddd9b5639766d48ecf5488340b9b667/container/Containerfile.fedora38#L32).

**Comment by astro-friedel** [comment]
From your first comment, I have added documentation that cmake, a C++ compiler, and generator (make, ninja, etc) needs to be present on the system, as well as adding the other dependencies to the default command line. These changes will be reflected in docker files in the next release. Also, as you found the docker files are to be generated from within the docker subdirectory (as the README.md file shows). 
As far as the 'formattable_pointer' errors go, these are from newer compilers only (I am guessing gcc 13+) and are only recently showing up for us (we develop on Ubuntu and only the most recent version 24.04 has gcc 13). These will be addressed in the next release as well.
